# https://hexo.io/docs/configuration

title: rebecca®
description: the digital home of rebecca turner, software engineer
author: rebecca turner
timezone: America/New_York
url: https://becca.ooo
permalink: :title/
skip_render:
  - "**/rustconf/**/*.{js,html,css}"
default_layout: post.njk
external_link: {enable: false} # Don't mess with external links (open in new tab)
theme: default
per_page: 0 # Disable pagination

# Plugin / extension config
marked:
  breaks: false
  modifyAnchors: 1
stylus: {compress: false}